name: minor
description: ''

inputs:
  token:
    description: "GitHub Token used to authenticate against a repository for Git context."
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: "${{ inputs.token }}"

    - name: 'Bump Repo Version'
      shell: bash
      run: |
        REMOTE_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
        CURRENT_VERSION="${REMOTE_VERSION:=0.0.0}"
        NEXT_VERSION=$(docker run alpine/semver semver -c -i minor ${CURRENT_VERSION});

        #git config user.name 'github-actions[bot]'
        #git config user.email 'github-actions[bot]@users.noreply.github.com'
        #yq '.version = "'${NEXT_VERSION}'"' -i charts/kubeforge/Chart.yaml 
        #git add charts/kubeforge/Chart.yaml
        #git commit -m "Bump Helm chart version to ${NEXT_VERSION}"

        # Tag the commit without [ci-skip]
        git tag "${NEXT_VERSION}"
        git push origin ${NEXT_VERSION}

        #git tag ${NEXT_VERSION};
        #git push --tags origin;
        #git commit --amend -m "Bump Helm chart version to ${NEXT_VERSION} / [skip ci]"
        #git push
