{{/*
############################################################
# Copyright (c) 2024 wsadza 
# Released under the MIT license
# ----------------------------------------------------------
#
############################################################
*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeforge.fullname" . }}
  labels:
    {{- include "kubeforge.labels" . | nindent 4 }}
rules:
  # Permissions for the custom resource in the "kubeforge.sh/v1" API group
  - apiGroups: ["kubeforge.sh"]  
    resources: ["overlays"] 
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]

  # Permissions for ConfigMaps in the "" (core) API group
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # Permissions for PersistentVolumes in the "" (core) API group
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # Permissions for PersistentVolumesClaims in the "" (core) API group
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # Permissions for Pods in the "" (core) API group
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # New rule for events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
...
