{{/*
############################################################
# Copyright (c) 2024 wsadza 
# Released under the MIT license
# ----------------------------------------------------------
#
############################################################
*/}}
---
{{- if .Values.kubeforge.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeforge.fullname" . }}-source-configuration
  labels:
    {{- include "kubeforge.labels" . | nindent 4 }}
data:
  sourceConfiguration.yaml: |
    {{ toYaml .Values.kubeforge.sourceConfiguration | nindent 4 }}
{{- end }}
...
