{{/*
############################################################
# Copyright (c) 2024 wsadza 
# Released under the MIT license
# ----------------------------------------------------------
#
############################################################
*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeforge.fullname" . }}
  labels:
    {{- include "kubeforge.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }} 
...
